apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-model-api3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api3
  template:
    metadata:
      labels:
        app: model-api3
    spec:
      containers:
      - name: model-api3
        imagePullPolicy: Always
        image: k8spipeline.azurecr.io/winequality:10
        command: ["python",  "deploy_mlflow.py"]
        ports:
        - containerPort: 5001
        
---

 
  
apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-api3 # rename to your service name
  name: model-api3 # rename to your service name
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: model-api3 # rename to your service name
  type: LoadBalancer
